/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MRP.PRESENTACION;

import MRP.Entidades.Item;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex T. Rivera
 */
public class NecesidadesNetasDLG extends javax.swing.JDialog {

    Dimension dim;
    JLabel txtPagina;
    List<Item> listaItems = new ArrayList<>();
    
    public NecesidadesNetasDLG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dim = super.getToolkit().getScreenSize();
        this.setSize(dim);
        this.txtPagina =  new JLabel();
        txtPagina.setSize(1300,700);
        editarEtiqueta();
        this.add(txtPagina);
    }
    
    public void setLComponentes(List<Item> lComponentes){
        this.listaItems = lComponentes;
    }

    public void editarEtiqueta(){
    String html = "";
    html += "<html>";
        html += "<head>";
        html += "</head>";
        
        html += "<body>";
        try {
            html += getTabla(listaItems.get(0));  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }

        html += "</body>";
        
    html += "</html>";
        
        txtPagina.setText(html);
    }
    
    public String getTabla(Item com){
        String html = "";
        html +="<table border='1'>";
            html +="<tr>";
                html +="<td>tamaño<br>del<br>lote</td>";
                html +="<td>Plazo</td>";
                html +="<td>disponible</td>";
                html +="<td>Stock de<br>seguridad</td>";
                html +="<td>Reservado</td>";
                html +="<td>Codigo<br>de nivel<br>inferior</td>";
                html +="<td>Identificacion<br>del articulo</td>";
                html +="<td>INDICADORES</td>";
                html +="<td colspan='24'>SEMANAS</td>";
            html +="</tr>";
            
            html +="<tr>";
            
            html +="</tr>";
            
        html +="</table>";
        
        return html;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
